volume:
  lowLimit: 2
  upLimit: 20
  step: 2
  interval: 6
  EC2VolumeId: vol-0b748cdfc3f2658b3
  rootDrive: /dev/xvda
  rootPart: /dev/xvda1
  rootPartNum: 1

proc:
  name: sidekiq
  memoryLimit: 2
