volumeFreespaceControl:
  enable: false
  minFreeSpace: 2
  maxVolumeSize: 20
  increaseStep: 2
  checkInterval: 5
  EC2VolumeId: vol-0b748cdfc3f2658b3
  EC2rootDrive: /dev/xvda
  EC2rootPart: /dev/xvda1
  EC2rootPartNum: 1

processMemoryControl:
  enable: true
  name: sidekiq
  stopLine: systemctl stop sidekiq
  startLine: systemctl start sidekiq
  memoryLimit: 2
  checkInterval: 5
