volume:
  enable: false
  lowLimit: 2
  upLimit: 20
  step: 2
  interval: 5
  EC2VolumeId: vol-0b748cdfc3f2658b3
  rootDrive: /dev/xvda
  rootPart: /dev/xvda1
  rootPartNum: 1

proc:
  enable: true
  name: sidekiq
  stopLine: systemctl stop sidekiq
  startLine: systemctl start sidekiq
  memoryLimit: 2
  interval: 5
