volume:
  enable: false
  lowLimit: 2
  upLimit: 20
  step: 2
  interval: 5
  EC2VolumeId: vol-0b748cdfc3f2658b3
  rootDrive: /dev/xvda
  rootPart: /dev/xvda1
  rootPartNum: 1

proc:
  enable: false
  name: chromium
  startLine: chromium
  memoryLimit: 2
  interval: 5
